---
role:
  pkg:
    # - name: coreutils
    #   os: ["alpine"]
    # - openssl
    - name: php
      action: install
      os: ["!jessie"]
    - name: php5
      action: install
      os: jessie # debian8
    # - name: php-composer
    #   os: ["archlinux"]
    # - name: homebrew/homebrew-php/php70
    #   os: ["darwin"]
    # - name: php7.0 php7.0-cli php7.0-fpm
    #   os: ["debian"]
    - name: composer
      os: ["!centos", "!jessie"]
  post_install:
    - php --version
    - command: ./install-composer.sh
      os: ["centos", "jessie"]
    - |
      PATH="$PATH:$HOME/bin"
      composer --version
    # - PATH="$HOME/.config/composer/vendor/bin:$PATH"
    # - export PATH=$PATH:~/.composer/vendor/bin
  post_remove:
    # rm "$HOME/bin/composer" || rm /usr/local/bin/composer
    - command: rm $(command -v composer)
      if: "hash composer"
      os: ["centos", "jessie"]
    # - command: rm -r ~/.composer
    #   if: '[ "${DOT_COMPOSER_CLEAR:-0}" -eq 1 ]'
    #   # os: ["centos", "jessie"]
