---
role:
  pkg:
    # - name: coreutils
    #   os: ["alpine"]
    # - openssl
    - php
    # - name: php-composer
    #   os: ["archlinux"]
    # - name: homebrew/homebrew-php/php70
    #   os: ["darwin"]
    # - name: php7.0 php7.0-cli php7.0-fpm
    #   os: ["debian"]
    - composer
  # post_install:
  #   - ./install-composer.sh
  #   # - PATH="$HOME/.config/composer/vendor/bin:$PATH"
  #   # - export PATH=$PATH:~/.composer/vendor/bin
