---
role:
  pkg:
    # - name: coreutils
    #   os: ["alpine"]
    # - openssl
    - name: php
      action: install
    # - name: php-composer
    #   os: ["archlinux"]
    # - name: homebrew/homebrew-php/php70
    #   os: ["darwin"]
    # - name: php7.0 php7.0-cli php7.0-fpm
    #   os: ["debian"]
    - name: composer
      os: ["!centos"]
  post_install:
    - php --version # || true
    - command: ./install-composer.sh
      os: ["centos"]
    - |
      PATH="$PATH:$HOME/bin"
      composer --version # || true
    # - PATH="$HOME/.config/composer/vendor/bin:$PATH"
    # - export PATH=$PATH:~/.composer/vendor/bin
  # post_remove:
  #   - command: # TODO: remove composer
  #     os: ["centos"]
