---
role:
  pkg:
    - name: busybox
      os: ["alpine"]
    - openssl
    - php
    # - name: php-composer
    #   os: ["archlinux"]
    # - name: homebrew/homebrew-php/php70
    #   os: ["darwin"]
    # - name: php7.0 php7.0-cli php7.0-fpm
    #   os: ["debian"]
  post_install:
    - ./install-composer.sh
    # - export PATH=$PATH:~/.composer/vendor/bin
